from pydantic import BaseModel, Field, validator
from typing import List, Optional
from enum import Enum
from datetime import datetime
from .data_models import AgentResponse


class ChatMode(str, Enum):
    """Enumeration for chat modes"""
    NORMAL = "normal"
    SELECTED_TEXT = "selected-text"


class ChatRequest(BaseModel):
    """Model for chat requests"""
    question: str = Field(..., description="The user's question about the book", min_length=1)
    selected_text: Optional[str] = Field(None, description="Optional selected text from the book for selected-text mode")
    mode: ChatMode = Field(default=ChatMode.NORMAL, description="Interaction mode - normal for semantic search, selected-text for focused analysis")

    @validator('question')
    def validate_question(cls, v):
        if not v or not v.strip():
            raise ValueError('Question cannot be empty')
        return v.strip()

    @validator('selected_text')
    def validate_selected_text(cls, v, values):
        if values.get('mode') == ChatMode.SELECTED_TEXT and (not v or not v.strip()):
            raise ValueError('Selected text cannot be empty in selected-text mode')
        return v.strip() if v else v


class ChatResponse(BaseModel):
    """Model for chat responses"""
    response_id: str = Field(..., description="Unique identifier for the response")
    answer: str = Field(..., description="The answer generated by the agent based on book content")
    sources: List[str] = Field(default_factory=list, description="List of book content IDs used to generate the answer")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level in the response")
    message: Optional[str] = Field(None, description="Additional message when information is not available in book")


class ChatResponseWithSelectedText(ChatResponse):
    """Extended response model that may include additional information for selected-text mode"""
    mode_used: ChatMode = Field(default=ChatMode.NORMAL, description="The mode that was used to generate the response")
    selected_text_used: Optional[str] = Field(None, description="The selected text that was used in selected-text mode")


class ErrorResponse(BaseModel):
    """Model for error responses"""
    error: str = Field(..., description="Error code")
    message: str = Field(..., description="Human-readable error message")


class StatusResponse(BaseModel):
    """Model for health check responses"""
    status: str = Field(..., description="Current health status", enum=["healthy", "degraded", "unavailable"])
    timestamp: datetime = Field(default_factory=datetime.now, description="When the status was checked")


class ProcessedQueryResult(BaseModel):
    """Model for the result of processing a user query"""
    query_id: str
    response: AgentResponse
    success: bool = True
    error_message: Optional[str] = None