from pydantic import BaseModel, Field
from typing import List, Dict, Optional
from datetime import datetime


class BookContent(BaseModel):
    """Model for book content sections"""
    id: str = Field(..., description="Unique identifier for each book section/chapter")
    title: str = Field(..., description="Title of the section/chapter")
    content: str = Field(..., description="Full text content of the section")
    embedding: Optional[List[float]] = Field(None, description="Vector representation of the content (from Cohere)")
    metadata: Dict = Field(default_factory=dict, description="Additional information like chapter number, section hierarchy")


class UserQuery(BaseModel):
    """Model for user queries"""
    query_id: str = Field(..., description="Unique identifier for the query session")
    question: str = Field(..., description="The user's question about the book")
    selected_text: Optional[str] = Field(None, description="Text selected by user for selected-text mode")
    mode: str = Field("normal", description="Interaction mode ('normal' or 'selected-text')")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the query was submitted")

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "query_id": "query_123",
                    "question": "What are the key principles of humanoid robotics?",
                    "mode": "normal"
                }
            ]
        }


class RetrievedContext(BaseModel):
    """Model for retrieved context from book"""
    context_id: str = Field(..., description="Unique identifier for the retrieved context")
    content: str = Field(..., description="The relevant book content retrieved from Qdrant")
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Semantic similarity score (0.0-1.0)")
    source_id: str = Field(..., description="Reference to the original book content ID")
    retrieval_metadata: Dict = Field(default_factory=dict, description="Additional metadata about the retrieval")


class AgentResponse(BaseModel):
    """Model for agent responses"""
    response_id: str = Field(..., description="Unique identifier for the response")
    query_id: str = Field(..., description="Reference to the original query")
    answer: str = Field(..., description="The final answer generated by the agent")
    sources: List[str] = Field(default_factory=list, description="List of book content IDs used to generate the answer")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level in the response (0.0-1.0)")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the response was generated")


class ChatSession(BaseModel):
    """Model for chat sessions"""
    session_id: str = Field(..., description="Unique identifier for the chat session")
    user_queries: List[UserQuery] = Field(default_factory=list, description="List of queries in the session")
    responses: List[AgentResponse] = Field(default_factory=list, description="List of responses in the session")
    created_at: datetime = Field(default_factory=datetime.now, description="When the session was created")
    last_accessed: datetime = Field(default_factory=datetime.now, description="When the session was last accessed")